### ISSUE TITLE
FSharp.Core.Open.FS31 unlisted from NuGet?

### ISSUE THREAD

**Issue by legomind** [YoloDev/YoloDev.FSharp.AspNet#12]
When running `dnu restore` I get:

```
  Unable to locate FSharp.Core.Open.FS31 >= 3.1.1.5
```

**Comment by Alxandr** [comment]
@legomind this project is beeing decommissioned. I rewrote from scratch (too much breaking changes) as [YoloDev.Dnx.FSharp](https://github.com/YoloDev/YoloDev.Dnx.FSharp). You can find it at the same myget feed. Though the API for compilers were changed yesterday (and nuget is wonkey today), so it might not work. If it doesn't though, you'll have a working version within a few days.

It was built and tested against beta5.

**Comment by legomind** [comment]
Thanks. May I sugest updating README?

**Comment by Alxandr** [comment]
Yeah. Also, if you'd like to help with documentation on the new project, I'd love to take some Readme PRs ^^

**Comment by legomind** [comment]
Absolutely. Ill create a PR once I get it working on my machine!
